const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
const ADD_GAME = 'ADD_GAME';
const SEARCH_GAME = 'SEARCH_GAME';
const GET_GENRES = 'GET_GENRES';
const GET_GAME_BY_ID = 'GET_GAME_BY_ID';

export {
    GET_VIDEOGAMES,
    ADD_GAME,
    SEARCH_GAME,
    GET_GENRES,
    GET_GAME_BY_ID
};